	const favoriteTags = [
		"lovey",
		"incest",
		"bath",
		"beach",
		"school",
		"virgin",
	];
	const Tags = {
		cen: ["censored"],
		pcen: ["partial censorship"],
		unc: ["un-censored"],
		busty: ["big breasts"],
		slim: ["small breasts"],
		one: ["oneshot"],
		lovey: ["happy sex", "romance", "*become lovers"],
		virgin: ["virgin*", "defloration"],
		serie: ["serialized"],
		milf: ["milf*"],
		cream: ["creampie"],
		ntr: ["cheating", "infidelity", "netorare"],
		bath: ["bath*"],
		shota: ["shotacon"],
		school: ["*school*", "*student*"],
		incest: ["incest", "*sister*", "*brother*", "*sibling*", "cousins"],
		sis: ["*sister*"],
		bro: ["*brother*"],
		sibl: ["*sibling*", "*sister*", "*brother*", "cousins"],
		xray: ["x-ray"],
		harem: ["harem"],
		sed: ["seduction"],
		loli: ["lolicon"],
		lesb: ["yuri*"],
		korean: ["webtoon", "korean comic"],
		rape: ["rape", "sexual abuse"],
		swap: ["gender bender"],
		doujin: ["doujinshi"],
		ecchi: ["ecchi"],
		anime: ["adapted to h-anime"],
		vr: ["virtual reality"],
		twin: ["twin*"],
		swim: ["swimsuit*", "bikini"],
		shy: ["shy characters"],
		friends: ["*friends*", "co-workers"],
		idol: ["idols"],
		spring: ["hot springs"],
		teen: ["*younger female"],
		color: ["full color"],
		beach: ["beach"],
	};